// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"example/token"
)

const (
	NoState    = -1
	NumStates  = 51
	NumSymbols = 62
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '.'
1: 'E'
2: '+'
3: '-'
4: 'i'
5: 'f'
6: 'p'
7: 'r'
8: 'o'
9: 'g'
10: 'r'
11: 'a'
12: 'm'
13: ':'
14: 'v'
15: 'a'
16: 'r'
17: ';'
18: ','
19: '{'
20: '}'
21: '='
22: 'i'
23: 'f'
24: '('
25: ')'
26: 'e'
27: 'l'
28: 's'
29: 'e'
30: '<'
31: '>'
32: '<'
33: '>'
34: '+'
35: '-'
36: '*'
37: '/'
38: 'i'
39: 'n'
40: 't'
41: 'f'
42: 'l'
43: 'o'
44: 'a'
45: 't'
46: 'p'
47: 'r'
48: 'i'
49: 'n'
50: 't'
51: '"'
52: '"'
53: ' '
54: '\t'
55: '\n'
56: '\r'
57: 'a'-'z'
58: 'a'-'z'
59: 'A'-'Z'
60: '0'-'9'
61: .
*/
